# This workflow can be used to fetch open issues with specific labels and create a new issue with a tasklist, referencing these issues.
# I personally use this for 1-1s with my manager. I have a label called "1-1 questions" and throughout the week I create issues for questions I want to ask.
# Then I can provide the link to this one issue where everything is linked and referenced during my 1-1s.
name: Tasklist automation

on:
  workflow_dispatch:
    
  schedule:
    - cron: '0 5 * * 2'  # Runs every Tuesday at 5am

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'xxx'
            });

            if (issues.length > 0) {
              const currentDate = new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
              const parentIssueTitle = `Issue Title - ${currentDate}`;

              let taskList = '```[tasklist]\n';
              taskList += '### Issues \n';
              for (const issue of issues) {
                taskList += `- [ ] ${issue.html_url}\n`;
              }
              const { data: parentIssue } = await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: parentIssueTitle,
                body: taskList,
              });
            }
